// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDva-9T_kOUFXHPBN0BbAiANtvWn1axQuM',
    appId: '1:232975692935:web:0e7691fc1e5323245f3422',
    messagingSenderId: '232975692935',
    projectId: 'instagramclone-4ac6a',
    authDomain: 'instagramclone-4ac6a.firebaseapp.com',
    storageBucket: 'instagramclone-4ac6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuL_gT-n16m406LuOqBhVMVKzMvy2yu4',
    appId: '1:232975692935:ios:e3a5e2cc67f6c9055f3422',
    messagingSenderId: '232975692935',
    projectId: 'instagramclone-4ac6a',
    storageBucket: 'instagramclone-4ac6a.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQuL_gT-n16m406LuOqBhVMVKzMvy2yu4',
    appId: '1:232975692935:ios:e3a5e2cc67f6c9055f3422',
    messagingSenderId: '232975692935',
    projectId: 'instagramclone-4ac6a',
    storageBucket: 'instagramclone-4ac6a.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDva-9T_kOUFXHPBN0BbAiANtvWn1axQuM',
    appId: '1:232975692935:web:4388ccd55ec50aec5f3422',
    messagingSenderId: '232975692935',
    projectId: 'instagramclone-4ac6a',
    authDomain: 'instagramclone-4ac6a.firebaseapp.com',
    storageBucket: 'instagramclone-4ac6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLz-RbmycL4jK8v_zN7Y3dbzcqaGA3hjg',
    appId: '1:232975692935:android:2cfa91dca80eda8b5f3422',
    messagingSenderId: '232975692935',
    projectId: 'instagramclone-4ac6a',
    storageBucket: 'instagramclone-4ac6a.appspot.com',
  );

}